# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
dist: xenial
sudo: false
addons:
  apt:
    packages:
    - dvipng
    - texlive
    - texlive-latex-extra
    - latexmk
matrix:
  include:
    - python: 3.7
      env: SPHINX_SPEC="==1.6.5" SPHINXOPTS=""
    - python: 3.7
    - python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install pytest pytest-cov numpy matplotlib sphinx${SPHINX_SPEC} codecov
script:
  - |
    python setup.py sdist
    cd dist
    pip install numpydoc* -v
  - pytest -v --pyargs numpydoc
  - |
    cd ../doc
    make SPHINXOPTS=$SPHINXOPTS html
    make SPHINXOPTS=$SPHINXOPTS latexpdf
after_script:
  - |
    cd ../dist
    codecov
